import { useState, useEffect, useRef, useCallback } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { FiBell } from 'react-icons/fi';
import toast from 'react-hot-toast';
import {
  listNotifications,
  markNotificationRead,
  markAllNotificationsRead,
  deleteNotification,
} from '../api/notifications';
import { formatDateTime } from '../utils/format';
import './NotificationBell.css';

const TYPE_LABELS = {
  low_stock: 'Low Stock',
  daily_report: 'Daily Report',
  weekly_report: 'Weekly Report',
  expiry: 'Expiry',
  payment_due: 'Payment Due',
  system: 'System',
};

export default function NotificationBell() {
  const [open, setOpen] = useState(false);
  const [notifications, setNotifications] = useState([]);
  const [unreadCount, setUnreadCount] = useState(0);
  const [loading, setLoading] = useState(false);
  const containerRef = useRef(null);

  const fetchNotifications = useCallback(async () => {
    try {
      const res = await listNotifications();
      setNotifications(res.data);
      setUnreadCount(res.unreadCount);
    } catch {
      // Silent - a failed poll shouldn't interrupt the cashier mid-sale
    }
  }, []);

  useEffect(() => {
    fetchNotifications();
    // Reports are generated by backend cron, so a slow poll is plenty
    const interval = setInterval(fetchNotifications, 120000);
    return () => clearInterval(interval);
  }, [fetchNotifications]);

  // Close on outside click
  useEffect(() => {
    if (!open) return undefined;
    const handleClick = (e) => {
      if (containerRef.current && !containerRef.current.contains(e.target)) setOpen(false);
    };
    document.addEventListener('mousedown', handleClick);
    return () => document.removeEventListener('mousedown', handleClick);
  }, [open]);

  const handleToggle = async () => {
    const next = !open;
    setOpen(next);
    if (next) {
      setLoading(true);
      await fetchNotifications();
      setLoading(false);
      // Opening the panel counts as having seen them - clear the badge like
      // any other notification bell, instead of leaving it stuck until each
      // item is clicked individually.
      handleMarkAll();
    }
  };

  const handleRead = async (notification) => {
    if (notification.isRead) return;
    // Optimistic: the badge should drop the moment it's tapped
    setNotifications((prev) => prev.map((n) => (n._id === notification._id ? { ...n, isRead: true } : n)));
    setUnreadCount((c) => Math.max(c - 1, 0));
    try {
      await markNotificationRead(notification._id);
    } catch {
      fetchNotifications(); // roll back to server truth
    }
  };

  const handleDelete = async (notification, e) => {
    e.stopPropagation();
    const wasUnread = !notification.isRead;
    setNotifications((prev) => prev.filter((n) => n._id !== notification._id));
    if (wasUnread) setUnreadCount((c) => Math.max(c - 1, 0));
    try {
      await deleteNotification(notification._id);
    } catch {
      toast.error('Could not delete notification');
      fetchNotifications(); // roll back to server truth
    }
  };

  const handleMarkAll = async () => {
    try {
      await markAllNotificationsRead();
      setNotifications((prev) => prev.map((n) => ({ ...n, isRead: true })));
      setUnreadCount(0);
    } catch {
      toast.error('Could not mark all as read');
    }
  };

  return (
    <div className="notif-wrap" ref={containerRef}>
      <button className="notif-bell" onClick={handleToggle} aria-label="Notifications">
        <FiBell size={18} aria-hidden="true" />
        {unreadCount > 0 && <span className="notif-badge">{unreadCount > 9 ? '9+' : unreadCount}</span>}
      </button>

      <AnimatePresence>
        {open && (
          <motion.div
            className="notif-panel"
            initial={{ opacity: 0, y: -6 }}
            animate={{ opacity: 1, y: 0 }}
            exit={{ opacity: 0, y: -6 }}
            transition={{ duration: 0.15 }}
          >
            <div className="notif-head">
              <span>Notifications</span>
              {unreadCount > 0 && (
                <button className="btn-link" onClick={handleMarkAll}>Mark all read</button>
              )}
            </div>

            <div className="notif-list">
              {loading ? (
                <p className="notif-empty">Loading...</p>
              ) : notifications.length === 0 ? (
                <p className="notif-empty">No notifications yet. Stock alerts and daily reports will appear here.</p>
              ) : (
                notifications.map((n) => (
                  <div
                    key={n._id}
                    role="button"
                    tabIndex={0}
                    className={n.isRead ? 'notif-item' : 'notif-item notif-item-unread'}
                    onClick={() => handleRead(n)}
                    onKeyDown={(e) => e.key === 'Enter' && handleRead(n)}
                  >
                    <div className="notif-item-top">
                      <span className="notif-type">{TYPE_LABELS[n.type] || n.type}</span>
                      <div className="notif-item-top-right">
                        <span className="notif-time">{formatDateTime(n.createdAt)}</span>
                        <button
                          className="notif-delete"
                          aria-label="Delete notification"
                          onClick={(e) => handleDelete(n, e)}
                        >
                          ×
                        </button>
                      </div>
                    </div>
                    <span className="notif-title">{n.title}</span>
                    {n.channel === 'whatsapp' && (
                      <span className={`notif-status notif-status-${n.deliveryStatus}`}>
                        WhatsApp: {n.deliveryStatus}
                      </span>
                    )}
                  </div>
                ))
              )}
            </div>
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  );
}
